# Generated by Django 5.2.1 on 2025-05-25 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(help_text='Unique student identifier (e.g., 202212312)', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('section', models.IntegerField(help_text="Student's section (e.g., 1, 2, 3)")),
                ('course', models.CharField(choices=[('BSIT', 'BSIT - Bachelor of Science in Information Technology'), ('BSCS', 'BSCS - Bachelor of Science in Computer Science'), ('BSCRIM', 'BSCRIM - Bachelor of Science in Criminology'), ('BSBM', 'BSBM - Bachelor of Science in Business Management'), ('BSED', 'BSED - Bachelor of Secondary Education'), ('BSHM', 'BSHM - Bachelor of Science in Hospitality Management'), ('BSP', 'BSP - Bachelor of Science in Psychology')], max_length=100)),
                ('year_level', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Profile picture of the student', null=True, upload_to='student_images/')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(help_text='Subject code (e.g., CS101)', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Full subject name (e.g., Computer Programming 1)', max_length=100, unique=True)),
                ('units', models.DecimalField(decimal_places=1, help_text='Number of academic units/credits', max_digits=3)),
                ('description', models.TextField(blank=True, help_text='Brief description of the subject content', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_grade', models.DecimalField(decimal_places=2, help_text='Grade for activities (0-100)', max_digits=5)),
                ('quiz_grade', models.DecimalField(decimal_places=2, help_text='Grade for quizzes (0-100)', max_digits=5)),
                ('exam_grade', models.DecimalField(decimal_places=2, help_text='Grade for exams (0-100)', max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.subject')),
            ],
            options={
                'ordering': ['student', 'subject'],
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
